import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '600'], // Choose weights you need
  variable: '--font-roboto', // Optional: for CSS variable usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className} ${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
